spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-name: kakao
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            redirect-uri: ${REDIRECT_URI}
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - profile_image
            client-authentication-method: client_secret_post
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  jwt:
    secret: ${JWT_SECRET}
  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379
server:
  servlet:
    context-path: /api
logging:
  level:
    org:
      springframework:
        security: debug
        web: debug
pay:
  admin-key: ${ADMIN_KEY}
  server-url: ${SERVER_URL}
  success-url: ${SUCCESS_URL}